"""adiciona localizacao e rotas

Revision ID: 16a656a6df32
Revises: 1437d251b628
Create Date: 2026-09-16 11:36:58.492092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a656a6df32'
down_revision = '1437d251b628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.String(length=500), server_default='', nullable=False))
        batch_op.add_column(sa.Column('cep', sa.String(length=20), server_default='', nullable=False))
        batch_op.add_column(sa.Column('cidade', sa.String(length=120), server_default='', nullable=False))
        batch_op.add_column(sa.Column('uf', sa.String(length=2), server_default='', nullable=False))
        batch_op.add_column(sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True))

    with op.batch_alter_table('motoboys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude_atual', sa.Numeric(precision=10, scale=7), nullable=True))
        batch_op.add_column(sa.Column('longitude_atual', sa.Numeric(precision=10, scale=7), nullable=True))
        batch_op.add_column(sa.Column('localizacao_atualizada_em', sa.DateTime(), nullable=True))

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cep_entrega', sa.String(length=20), server_default='', nullable=False))
        batch_op.add_column(sa.Column('cidade_entrega', sa.String(length=120), server_default='', nullable=False))
        batch_op.add_column(sa.Column('uf_entrega', sa.String(length=2), server_default='', nullable=False))
        batch_op.add_column(sa.Column('latitude_entrega', sa.Numeric(precision=10, scale=7), nullable=True))
        batch_op.add_column(sa.Column('longitude_entrega', sa.Numeric(precision=10, scale=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('longitude_entrega')
        batch_op.drop_column('latitude_entrega')
        batch_op.drop_column('uf_entrega')
        batch_op.drop_column('cidade_entrega')
        batch_op.drop_column('cep_entrega')

    with op.batch_alter_table('motoboys', schema=None) as batch_op:
        batch_op.drop_column('localizacao_atualizada_em')
        batch_op.drop_column('longitude_atual')
        batch_op.drop_column('latitude_atual')

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('uf')
        batch_op.drop_column('cidade')
        batch_op.drop_column('cep')
        batch_op.drop_column('endereco')

    # ### end Alembic commands ###
