"""cria tabelas de pedidos

Revision ID: 8fcc109468b2
Revises: 
Create Date: 2026-08-31 12:18:48.753995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fcc109468b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('endereco', sa.String(length=500), nullable=False),
    sa.Column('pagamento', sa.String(length=200), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('hora_inicio_preparo', sa.DateTime(), nullable=True),
    sa.Column('hora_pronto', sa.DateTime(), nullable=True),
    sa.Column('hora_saida_entrega', sa.DateTime(), nullable=True),
    sa.Column('hora_finalizado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('setor', sa.String(length=100), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('retirados', sa.JSON(), nullable=False),
    sa.Column('adicionais', sa.JSON(), nullable=False),
    sa.Column('valor_adicionais', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('molho', sa.String(length=100), nullable=False),
    sa.Column('preparo_suco', sa.String(length=50), nullable=False),
    sa.Column('acucar_suco', sa.String(length=50), nullable=False),
    sa.Column('observacao', sa.String(length=300), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_pedido')
    op.drop_table('pedidos')
    # ### end Alembic commands ###
