"""estrutura empresa pedidos e itens

Revision ID: 914c968e5b53
Revises: 8fcc109468b2
Create Date: 2026-08-31 13:50:06.300727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "914c968e5b53"
down_revision = "8fcc109468b2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "empresas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("ativa", sa.Boolean(), nullable=False),
        sa.Column("criada_em", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table("empresas", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_empresas_slug"),
            ["slug"],
            unique=True,
        )

    with op.batch_alter_table("itens_pedido", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_itens_pedido_pedido_id"),
            ["pedido_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_itens_pedido_produto_id"),
            ["produto_id"],
            unique=False,
        )

    with op.batch_alter_table("pedidos", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("empresa_id", sa.Integer(), nullable=True)
        )

        batch_op.create_index(
            batch_op.f("ix_pedidos_data_hora"),
            ["data_hora"],
            unique=False,
        )

        batch_op.create_index(
            batch_op.f("ix_pedidos_empresa_id"),
            ["empresa_id"],
            unique=False,
        )

        batch_op.create_index(
            batch_op.f("ix_pedidos_status"),
            ["status"],
            unique=False,
        )

        batch_op.create_foreign_key(
            "fk_pedidos_empresa_id",
            "empresas",
            ["empresa_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("pedidos", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_pedidos_empresa_id",
            type_="foreignkey",
        )

        batch_op.drop_index(
            batch_op.f("ix_pedidos_status")
        )

        batch_op.drop_index(
            batch_op.f("ix_pedidos_empresa_id")
        )

        batch_op.drop_index(
            batch_op.f("ix_pedidos_data_hora")
        )

        batch_op.drop_column(
            "empresa_id"
        )

    with op.batch_alter_table("itens_pedido", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_itens_pedido_produto_id")
        )

        batch_op.drop_index(
            batch_op.f("ix_itens_pedido_pedido_id")
        )

    with op.batch_alter_table("empresas", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_empresas_slug")
        )

    op.drop_table("empresas")

    # ### end Alembic commands ###