"""adiciona bairros e taxa de entrega

Revision ID: bb33bc627e3b
Revises: 914c968e5b53
Create Date: 2026-09-08 11:58:05.292806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb33bc627e3b'
down_revision = '914c968e5b53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bairros_entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('taxa', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nome', name='uq_bairro_entrega_empresa_nome')
    )
    with op.batch_alter_table('bairros_entrega', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bairros_entrega_empresa_id'), ['empresa_id'], unique=False)

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bairro_entrega', sa.String(length=120), server_default='', nullable=False))
        batch_op.add_column(sa.Column('taxa_entrega', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('taxa_entrega')
        batch_op.drop_column('bairro_entrega')

    with op.batch_alter_table('bairros_entrega', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bairros_entrega_empresa_id'))

    op.drop_table('bairros_entrega')
    # ### end Alembic commands ###
