"""adiciona sabor suco

Revision ID: ffeb5287d008
Revises: bb33bc627e3b
Create Date: 2026-09-09 08:36:14.617835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffeb5287d008'
down_revision = 'bb33bc627e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sabor_suco', sa.String(length=80), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_pedido', schema=None) as batch_op:
        batch_op.drop_column('sabor_suco')

    # ### end Alembic commands ###
